### ISSUE TITLE
Customize a list of instances to randomize from

### ISSUE THREAD

**Issue by austinhuang0131** [SimonBrazell/privacy-redirect#111]
Related to #101, tag enhancement please

As of now, instance lists are hard-coded in `background.js`. It may be a bit complicated, but since instances may (very frequently) temporarily stop working, wouldn't it be convenient to have a customizable instance list?

**Comment by SimonBrazell** [comment]
Yeah I think this is a necessity now given how unreliable  all the instances are, I'll keep this in mind when I next put some time into this project.

**Comment by tiotrom** [comment]
Yes this can be a solution! Like I suggested before the best idea would be to pull instances from external lists that are maintained by others - they can check them, edit them, and all that. So the Privacy Redirect does not have to deal with all of these. I am one of those who can keep an eye on these instances and even find more, if it would be an easy way for me to do that.

**Comment by SimonBrazell** [comment]
I was thinking of just making the random instance lists configurable via the options, rather than hard coded as they are currently, then users can add whatever they like. However if you want to maintain a list of working instances that would certainly help, I've just been using the list on [https://invidio.us/](https://invidio.us/) but they are still fairly unreliable it seems.

**Comment by austinhuang0131** [comment]
An easy solution would be parsing `a.com; b.com` for each instance address field

**Comment by SimonBrazell** [comment]
Yeah I was thinking of either 

- extending the existing instance inputs, allowing entry of comma separated values as well as single instances or 

- adding a new input that exposes the currently configured random instance pool, also comma separated.

**Comment by tiotrom** [comment]
I think an external list of urls would be great since I and others can help to keep it updated. But needs to be easy to edit, maybe like a "vote" system saying this works, this doesn't. Idk....

**Comment by SimonBrazell** [comment]
Could maybe just use a Github wiki page perhaps?

**Comment by austinhuang0131** [comment]
Maybe as a separate repo (it could be of interest for other people) with markdown tables.

Probably not privacy-friendly to keep pinging the list, so static markdown files are enough.

**Comment by tiotrom** [comment]
Would be great to have a way to "vote" or something the like, so that we can, in time, give a score to which ones are more reliable or not. If that's too complicated then I can help with whatever even if it is a github wiki page. I can remove the ones that do not work and update with the ones that work, since I am using Invidious daily.

**Comment by austinhuang0131** [comment]
You can use issue reactions to vote

which is why it should use a different repo
