### ISSUE TITLE
FreeTube opens without clicking on link

### ISSUE THREAD

**Issue by ToughGuyKunio** [SimonBrazell/privacy-redirect#122]
It seems FreeTube can be opened by just visiting a site (not clicking on a link).
When I visit https://feber.se/ it opens FreeTube, after that FreeTube keeps loading for a long time, and finally gives an invidious error message.

**Comment by SimonBrazell** [comment]
Just tried this out, only seems to affect Firefox, I know what it is, there is a request going out for the YouTube player API which triggers the redirect. Need to change the filter so that it only redirects to FreeTube for the `main_frame` context. I'll fix it up in the next release.

Thanks @ToughGuyKunio!

**Comment by SimonBrazell** [comment]
This should be fixed in v1.1.43.
