### ISSUE TITLE
[Feat Req] Option to add custom Redirects

### ISSUE THREAD

**Issue by Sepero** [SimonBrazell/privacy-redirect#267]
I'd like to Redirect all links from Wikipedia to Infogalactic.com, but for reasons other than "privacy".

It would be good if we could add in custom redirects. Thank you

**Comment by Kotuklion** [comment]
Maybe you could supplement your Privacy Redirect extension with other one that supports custom redirects, for example [Redirector](https://github.com/einaregilsson/Redirector)? I think the main function of Privacy Redirect is providing reliable alternatives for disrespectful frontends, rather than the whole redirect mechanism.

**Comment by Sepero** [comment]
Excellent. I didn't know about Redirector. I have it installed now. Thank you
