### ISSUE TITLE
Randomise the Bibliogram instance on first install

### ISSUE THREAD

**Issue by cloudrac3r** [SimonBrazell/privacy-redirect#34]
Developer of Bibliogram here, again.

To reduce the volume of requests from users to a single instance, I'd prefer if you randomly selected a trusted instance from a list as the default when someone first installs the extension.

I suggest choosing from this list:

- https://bibliogram.art
- https://bibliogram.snopyta.org
- https://bibliogram.pussthecat.org

However, you should contact the developer of pussthecat.org before adding their instance to this initial list to make sure they're okay with the volume of traffic they may receive. I (bibliogram.art) and perflyst (snopyta.org) are already both okay with this.

**Comment by SimonBrazell** [comment]
Yes I can certainly do this, I'm thinking that I could store an array of instances in the extension and randomly pick one when the extension is installed, making it the default for that installation, otherwise it might get confusing for users if they are continually redirected to a different server each time. How does that sound?

On the matter of consent to use the servers I'm sorry again for not reaching out to you, I didn't really consider this, I think I just assumed that because they were listed on the wiki they were available for public use, I made the same assumption for all the services to be honest... I should probably try contact all the instance owners now to see if they are okay with these redirects. Thank you for raising this issue, not something I thought about before.

**Comment by cloudrac3r** [comment]
> I'm thinking that I could store an array of instances...

Good plan.

There's also the [instances API](https://github.com/cloudrac3r/bibliogram/wiki/API:-instances) that you could get data from if you wanted to, but seeing as the data comes from a publicly editable wiki, maybe it's not the best idea. I'll let you read that link and decide for yourself.

> On the matter of consent to use the servers...

It's all good. They are listed on the public wiki for a reason. :D It would be _nice_ to ask people before sending 1000 users to them, but I'm not super worried.

**Comment by SimonBrazell** [comment]
> There's also the instances API 

I noticed this last night, and the caveat about it being publicly editable, I think I'll just maintain a list in the extension for now, the users are free to refer to the wiki and enter a custom instance if they like anyway.

> It would be nice to ask people before sending 1000 users to them

Point taken. This extension has kinda had a bump in popularity lately for some reason... let me know if there is anything else I can do to help with the load.

**Comment by SimonBrazell** [comment]
This also has been added to [v1.1.21](https://github.com/SimonBrazell/privacy-redirect/releases/tag/v1.1.21).
