### ISSUE TITLE
Support for Firefox on Android

### ISSUE THREAD

**Issue by hmlendea** [SimonBrazell/privacy-redirect#367]
Hello,

Will you make this extension available for Firefox on Android?

Thanks.

**Comment by pinpontitit** [comment]
It's already possible to install this extension in Android if you use Firefox "Nightly", or Mull, or Fennec.
There are tutorials on the web if you want to know how to proceed. Type something like "how to install extensions in firefox nightly android".

I tried this extension on my phone and it works.

I don't think its up to the "Privacy Redirect" developer to choose if its extension is available to Firefox.
I think its actually Firefox that blocks all the extensions that weren't tested and validated thoroughly for Android, but they allow it in "Nightly" because it's the unstable development version of Firefox. 
And the two other browsers mentioned above(which I recommend by the way), being independant Firefox-based projects, allow all extensions installation by default.

**Comment by hmlendea** [comment]
Thank you!

I didn't know about this. It works wonderfully!

I went with Firefox Nightly for now. I will consider other browsers at a later time.
Also, since I use Nova Launcher I could just edit the Firefox Nightly icon to look and be named exactly like vanilla Firefox, which is nice. This way nothing feels changed except having more addons available and the in-app logo (which is rarely seen) is still blue.

I will close this now. Hopefully Mozilla will verify and whitelist this addon officially so that it will be available to the masses, but until then, this is a real solution.
