### ISSUE TITLE
[Feature Request] HTTP login support

### ISSUE THREAD

**Issue by TheFrenchGhosty** [SimonBrazell/privacy-redirect#49]
My Invidious instance (https://invidious.pussthecat.org) is semi-private and behind an HTTP login.

Privacy Redirect (and Invidition see [the related issue](https://codeberg.org/Booteille/Invidition/issues/44)) doesn't support it and automatically rewrite the instances links removing the login.

It would be really nice if it was supported.

**Comment by SimonBrazell** [comment]
Hi @TheFrenchGhosty should be able to do that, do you have any more details regarding the login mechanism, what is being removed, is it something in the URL params or elsewhere?

**Comment by TheFrenchGhosty** [comment]
It's something before the actual URL: for example for my instance https://invidious.pussthecat.org the URL will become https://username:password@invidious.pussthecat.org so Privacy Redirect just need to support links containing this syntax.

**Comment by SimonBrazell** [comment]
Okay I can see the problem now, so I imagine you've tried setting the Invidious instance as that URL, which isn't working because there is some basic 'validation' on the instance inputs that converts the entered URL string to a URL object and then stores only the `origin` attribute (https://invidious.pussthecat.org), stripping out any extra parts of the URL that the user might have accidentally included. I imagine that Invidition is doing the same.

I can make it so the validation checks for the presence of a username and password in the URL object and adds them to the origin if present, should be no problem.

**Comment by TheFrenchGhosty** [comment]
>Okay I can see the problem now, so I imagine you've tried setting the Invidious instance as that URL, which isn't working because there is some basic 'validation' on the instance inputs that converts the entered URL string to a URL object and then stores only the origin attribute (https://invidious.pussthecat.org), stripping out any extra parts of the URL that the user might have accidentally included. I imagine that Invidition is doing the same.

That's exactly the problem yeah both Invidition / Privacy Redirect rewrite the URL without the login.

To be honest I personally prefer if the issue was fixed on Invidition (since I prefer it's UI) but I guess if it's fixed on Privacy Redirect I will have to use it for now (this fix would also be useful in case some people use a similar setup/are using my instance).

**Comment by SimonBrazell** [comment]
[v1.1.26](https://github.com/SimonBrazell/privacy-redirect/releases/tag/v1.1.26) should allow you to do this now, let me know if you have any issues with it.

**Comment by SimonBrazell** [comment]
Noticed I only applied this for the popup, I'll do the same fix for the options menu in the next build.

**Comment by TheFrenchGhosty** [comment]
Thank you!
